ecommerce/cart/urls.py
from django.contrib import admin
from django.urls import path
from cart import views
app_name='cart'
urlpatterns = [
    path('cart/<int:i>',views.addtocart,name="cart"),
    path('cartview',views.cart_view,name="cartview"),
    path('cartremove/<int:i>',views.cart_remove,name="cartremove"),
    path('cartdelete/<int:i>', views.cart_delete, name="cartdelete"),
    path('checkout',views.checkout_form,name="checkout"),
    path('status/<u>', views.payment_status, name="status"),
    path('yourorders', views.your_orders, name="orders"),


]

ecommerce/ecommerce/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('shop.urls')),
    path('search',include('search.urls')),
    path('cart/',include('cart.urls')),
]

ecommerce/search/urls.py
from django.contrib import admin
from django.urls import path
from search import views
app_name="search"
urlpatterns = [
   path('',views.search_products,name="search")
]

ecommerce/shop/urls.py
from django.contrib import admin
from django.urls import path
from shop import views
app_name="shop"

from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('',views.allcategories,name="categories"),
    path('products/<int:p>',views.allproducts,name="products"),
    path('detail/<int:q>',views.alldetails,name="details"),
    path('reg', views.register, name="register"),
    path('login', views.user_login, name="login"),
    path('logout', views.user_logout, name="logout"),
    path('addcategory', views.add_category, name="category"),
    path('addproduct', views.add_product, name="product"),
    path('addstock/<int:i>', views.add_stock, name="stock"),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

ecommerce/cart/models.py
from django.db import models
from shop.models import Product
from django.contrib.auth.models import User
# Create your models here.
class Cart(models.Model):
    product=models.ForeignKey(Product,on_delete=models.CASCADE)
    user=models.ForeignKey(User,on_delete=models.CASCADE)
    quantity=models.IntegerField(default=1)
    date_add=models.DateTimeField(auto_now_add=True)

    def subtotal(self):
        return self.product.price*self.quantity

class Order_details(models.Model):
    product=models.ForeignKey(Product,on_delete=models.CASCADE)
    user=models.ForeignKey(User,on_delete=models.CASCADE)
    no_of_items=models.IntegerField()
    address=models.TextField()
    phone_no=models.BigIntegerField()
    pin=models.IntegerField()

    order_id=models.CharField(max_length=20, blank=True)
    ordered_date=models.DateTimeField(auto_now_add=True)

    payment_status=models.CharField(max_length=20,default="pending")
    delivery_status=models.CharField(max_length=20,default="pending")

class Payment(models.Model):
    name=models.CharField(max_length=20)
    amount=models.IntegerField()
    order_id=models.CharField(max_length=20,blank=True)
    razorpay_payment_id=models.CharField(max_length=20,blank=True)
    paid=models.BooleanField(default=False)

ecommerce/search/models.py
from django.db import models

# Create your models here.

ecommerce/cart/views.py
from django.shortcuts import render,redirect
from django.contrib.auth.decorators import login_required
from cart.models import Cart,Payment,Order_details,User
from shop.models import Product
from django.contrib.auth import login

import razorpay
@login_required
def addtocart(request,i):
    p=Product.objects.get(id=i)
    u=request.user
    try:
        c=Cart.objects.get(user=u,product=p)   # checks the product present in the cart table for a particular user
        if(p.stock>0):
            c.quantity+=1                          # if present it will increment the quantity of product
            c.save()
            p.stock-=1
            p.save()
    except:
        if(p.stock>0): # if not present then it will create a new record inside the cart table with quantity=1
           c=Cart.objects.create(product=p,user=u,quantity=1)
           c.save()
           p.stock-=1
           p.save()


    return redirect('cart:cartview')

def cart_view(request):
    u=request.user
    total=0
    c=Cart.objects.filter(user=u)
    for i in c:
        total+=i.quantity*i.product.price
    context={'cart':c,'total':total}

    return render(request,"cart.html",context)

@login_required
def cart_remove(request,i):
    p=Product.objects.get(id=i)
    u=request.user
    try:
        c=Cart.objects.get(user=u,product=p)
        if(c.quantity>1):
            c.quantity-=1
            c.save()
            p.stock+=1
            p.save()
        else:
            c.delete()
            p.stock+=1
            p.save()

    except:
        pass

    return redirect('cart:cartview')

@login_required
def cart_delete(request,i):
    p=Product.objects.get(id=i)
    u=request.user
    try:
        c=Cart.objects.get(user=u,product=p)
        if(c.quantity>1):
            c.quantity-=1
            c.save()
            p.stock+=Cart.quantity
            p.save()
        else:
            c.delete()
            p.stock+=Cart.quantity
            p.save()

    except:
        pass

    return redirect('cart:cartview')


@login_required

def checkout_form(request):
    if(request.method=="POST"):
        address=request.POST.get('a')
        phone=request.POST.get('p')
        pin=request.POST.get('pi')

        u=request.user

        c=Cart.objects.filter(user=u)

        total=0

        for i in c:
            total+=i.quantity*i.product.price
        total=int(total*100)

        client=razorpay.Client(auth=('rzp_test_nnlp4dQwHnRlZv','LHgyDXPbArGckg9xRIeeEGIF'))    # create a client connection

            # using razorpay id and secret code

        response_payment=client.order.create(dict(amount=total,currency="INR")) #create an order with
        # razorpay using razorpay client
        # print(response_payment)
        order_id=response_payment['id']
        order_status=response_payment['status']
        if(order_status=="created"):
            p=Payment.objects.create(name=u.username,amount=total,order_id=order_id)
            p.save()
            for i in c:
                o=Order_details.objects.create(product=i.product,user=u,no_of_items=i.quantity,address=address,phone_no=phone,pin=pin,order_id=order_id)
                o.save()
        else:
            pass

        response_payment['name']=u.username
        context={'payment':response_payment}

        return render(request,'payment.html',context)

    return render(request,'order.html')
from django.views.decorators.csrf import csrf_exempt
@csrf_exempt
def payment_status(request,u):
    user= User.objects.get(username=u)
    if(not request.user.is_authenticated):  #if user is not authenticated
        login(request,user)  #allowing requset user to login


    if(request.method=="POST"):
        response=request.POST
        print(response)
        print(u)

        param_dict={
            'razorpay_order_id':response['razorpay_order_id'],
            'razorpay_payment_id':response['razorpay_payment_id'],
            'razorpay_signature':response['razorpay_signature']
        }
        client=razorpay.Client(auth=('rzp_test_nnlp4dQwHnRlZv', 'LHgyDXPbArGckg9xRIeeEGIF'))  # create a client connection
        print(client)
        try:
            status=client.utility.verify_payment_signature(param_dict)  #to check the authenticity of the razorpay signature
            print(status)
            # To retrieve a particular record in Payment Table whose order id matches the response order id
            p=Payment.objects.get(order_id=response['razorpay_order_id'])
            p.razorpay_payment_id=response['razorpay_payment_id'] # add the payment id after successful payment
            p.paid=True # changes the pais status to True
            p.save()
            user=User.objects.get(username=u)
            print(user.username)
            o=Order_details.objects.filter(user=user,order_id=response['razorpay_order_id']) # retrieve the records in order_details
            #matching the current user and response_id.
            print(o)
            for i in o:
                i.payment_status="paid"
                i.save()

            #After successful payment deletes the items  in cart for a particular user
            c=Cart.objects.filter(user=user)
            c.delete()

        except:
            pass

    return render(request,'payment_status.html',{'status':status})

@login_required
def your_orders(request):
    u=request.user
    o=Order_details.objects.filter(user=u,payment_status="paid")
    context={'orders':o ,'name':u.username}
    return render(request,'yourorders.html',context)

ecommerce/search/views.py
from django.shortcuts import render
from shop.models import Product
from django.db.models import Q
# Create your views here.
def search_products(request):
    query=""
    p=None
    if(request.method=="POST"):
        query=request.POST.get('q')

        if(query):
            p=Product.objects.filter(Q(name__icontains=query) | Q(desc__icontains=query))

    return render(request,"search.html",{'product':p,'q':query})

ecommerce/templates/addcategory.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div  style="margin-bottom:100px">

<h2 class="text-center"> Add Categories Here....</h2>
<form method="POST" enctype="multipart/form-data">

{% csrf_token %}

<div class="mb-5 mx-auto " style="width:60%">
  <label  class="form-label">Name:</label>
  <input type="text" class="form-control" name="n" placeholder="Enter the Name">
</div>
    <div class="mb-3 mx-auto" style="width:60%">
  <label  class="form-label">Description</label>
  <input type="text" class="form-control" name="d" placeholder="Enter the description">
</div>

    <div class="mb-3 mx-auto" style="width:60%">
  <label  class="form-label">Image</label>
        <img src="{{product.image.url}}">
  <input type="file" class="form-control" name="i">
</div>


      <div class="mb-3  text-center">
  <input type="submit" value="submit">
</div>

</form>
</div>
{% endblock %}

ecommerce/templates/addstock.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="container">
    <h2 class="text-center"> Add Stock Here...</h2>
    <form method="POST">

{% csrf_token %}
  <div class="mb-3 mx-auto" style="width:30%">
  <label  class="form-label">Stock</label>
  <input type="number" class="form-control"  value="{{pro.stock}}" name="s" placeholder="Enter the stock">
</div>
 <div class="mb-3 text-center mx-auto">
  <input type="submit" value="submit">
</div>
    </form>
</div>
{% endblock %}

ecommerce/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.6.0/css/all.min.css" integrity="sha512-Kc323vGBEqzTmouAECnVceyQqyqdsSiqLQISBL29aUW4U/M7pSPA/gEUZQqv1cwx4OnYxTxve5UMg5GT6L4JJg==" crossorigin="anonymous" referrerpolicy="no-referrer" />
</head>
<body style="background-color:#cbaddb;">
<div class="container-fluid text-center mt-5">
    <img src="{% static 'images/logo2.png' %}" class="rounded-circle" height="150px" width="100px">
</div>
<header>
<nav class="navbar navbar-expand-lg navbar-light mt-5" style="background-color:#d5ccd9">
  <div class="container-fluid">
    <a class="navbar-brand fs-2 fw-bold" href="#">MyShop</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0 fs-5 ">
        <li class="nav-item">
          <a class="nav-link active fw-bold" aria-current="page" href="{% url 'shop:categories' %}">Home</a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle fw-bold" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Allcategories
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
              {% for i in links %}
            <li><a class="dropdown-item" href="{% url 'shop:products' i.id %}">{{i.name}}</a></li>
            {% endfor %}
          </ul>
            </li>
            {% if user.is_authenticated %}
<!--          #Normal user-->
            {% if user.is_superuser == False %}
          <li class="nav-item">
          <a class="nav-link active fw-bold" aria-current="page" href="{% url 'cart:cartview' %}"><i class="fa-solid fa-cart-shopping"><sup class="mx-2 text-danger fs-5">{{c}}</sup></i></a>
        </li>
              <li class="nav-item">
          <a class="nav-link active fw-bold" aria-current="page" href="{% url 'cart:orders' %}">YourOrders</a>
          </li>
          {% else %}
              <li class="nav-item">
          <a class="nav-link active fw-bold" aria-current="page" href="{% url 'shop:category' %}">Add Categories</a>
          </li>
              <li class="nav-item">
          <a class="nav-link active fw-bold" aria-current="page" href="{% url 'shop:product' %}">Add Products</a>
          </li>
          {% endif %}

          <li class="nav-item">
          <a class="nav-link active fw-bold" aria-current="page" href="{% url 'shop:logout' %}">Logout</a>
        </li>
          {% else %}
           <li class="nav-item">
          <a class="nav-link active fw-bold" aria-current="page" href="{% url 'shop:register' %}">Register</a>
        </li>
          <li class="nav-item">
          <a class="nav-link active fw-bold" aria-current="page" href="{% url 'shop:login' %}">Login</a>
          </li>

   {% endif %}

      </ul>
      <form class="d-flex" method="POST" action="{% url 'search:search' %}">
          {% csrf_token %}
        <input class="form-control me-2" type="search" placeholder="Search" name="q" aria-label="Search">
        <button class="btn btn-outline-dark" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>
</header>
<div class="container-fluid">
{% block content %}
{% endblock %}
</div>

<footer class="footer pt-1">
    <p class="text-center fs-5"><i class="fa fa-copyright me-1" aria-hidden="true"></i>myshop@pvt.Ltd</p>
</footer>
</body>
</html>

ecommerce/templates/cart.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="container text-center mt-5">
<h2 class="shadow">Shopping Cart</h2>
    <div class="row mt-5">
        <div class="col-7">
            <table class="table table-bordered border-1 shadow">
                <tr>
                   <th colspan="6">Cart Items</th>
                </tr>
                {% for i in cart %}
                <tr class="fs-6 fw-bold">
                    <td><img src="{{i.product.image.url}}" height="100px; width=100px;"></td>
                    <td>{{i.product.name}}</td>
                    <td>Unit Price: ₹{{i.product.price}}<br>
                    quantity: {{i.quantity}}</td>
                    <td>Subtotal: {{i.subtotal}}</td>
                    <td>
                        {% if i.product.stock > 0 %}
                        <a href="{% url 'cart:cart' i.product.id %}"><i class="fa-solid fa-square-plus fs-5 text-success"></i></a>
                        <a href="{% url 'cart:cartremove' i.product.id %}"><i class="fa-solid fa-square-minus fs-5 text-danger"></i></a>
                        <a href="{% url 'cart:cartdelete' i.product.id %}"><i class="fa-solid fa-trash fs-5 text-primary"></i></a>
                    {% else %}
                         <a href="{% url 'cart:cartremove' i.product.id %}"><i class="fa-solid fa-square-minus fs-5 text-danger"></i></a>
                        <a href="{% url 'cart:cartdelete' i.product.id %}"><i class="fa-solid fa-trash fs-5 text-primary"></i></a>

                        {% endif %}
                    </td>

                </tr>
                {% endfor %}
            </table>
        </div>
        <div class="col-4">
                   <table class="table table-bordered border-1 shadow">
                <tr>
                   <th colspan="4">Check Out</th>
                </tr>
                       <tr>
                           <td class="fw-bold">Total Price: {{total}}</td>
                       </tr>
            </table>
            <div class="d-flex justify-content-between mt-5">
            <a href="{% url 'cart:checkout' %}" class="btn btn-warning shadow">Buy Now</a>
            <a href="{% url 'shop:categories' %}" class="btn btn-warning shadow">Continue Shopping</a>
                </div>
        </div>

    </div>

</div>
{% endblock %}

ecommerce/templates/category.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<div class="row mt-3">
    <div class="col-12">
    <img src="{% static 'images/banner1.jpeg' %}" height="400px" width="100%"></div>
</div>

    <div class="row mt-3 px-3" style="margin-bottom:100px">
        <div class="col-12">
            <h3 class="text-center fw-bold text=light mt-5 mb-5 shadow">Big Billion Sale</h3>
            <p style="text-align:justify;line-height:2.5" class="fs-5">Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum</p>
        </div>
    </div>


<div class="container mt-5 mb-5">
    <div class="row">
{% for i in cat %}
        <div class="col-sm-4">
      <div class="card mx-auto border border-3 border-light" style="width:20rem;">
  <img src="{{i.image.url}}"  height="200px" width="100%" class="card-img-top" alt="...">
  <div class="card-body text-center">
    <h5 class="card-title">{{i.name}}</h5>

    <a href="{% url 'shop:products' i.id %}" class="btn btn-secondary">Products</a>
  </div>
</div>
        </div>

        {% endfor %}


    </div>
</div>



{% endblock %}

ecommerce/templates/detail.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="container mt-5" style="margin-bottom:100px">
<div class="card mb-3 mx-auto" style="max-width:50%;  background-color:#66246e">
  <div class="row g-0">
    <div class="col-md-4 p-3" style="background-color:#66246e">
      <img src="{{product.image.url}}" height="200px" width="100%" class="card-img-top" alt="...">
    </div>
    <div class="col-md-8">
      <div class="card-body">
          <h5 class="card-title" style="line-height:2">{{product.name}}</h5>
          <h5 class="card-title">{{product.desc}}</h5>
          <h5 class="card-title">₹{{product.price}}</h5>
          <h5 class="card-title"> {{product.stock}}</h5>
          <h5 class="card-title">{{product.available}}</h5>
          {% if user.is_superuser == True %}
           {% if product.stock > 0 %}
          <h5> Product in Stock </h5>
          <a href="{% url 'shop:stock'  product.id %}" class="btn btn-success">ADD STOCK</a>
          {% else %}
          <h5 class="text-danger">Product Out Of Stock</h5>
          <a href="{% url 'shop:stock' product.id %}" class="btn btn-success">ADD STOCK</a>
          {% endif %}

          {% else %}
          {% if product.stock > 0 %}
          <h5>Product in Stock</h5>
          <a href="{% url 'cart:cart' product.id %}" class="btn btn-success">ADD TO CART</a>
          {% else %}
          <h5 class="text-danger">Out Of Stock</h5>
          {% endif %}
          {% endif %}

      </div>
    </div>
  </div>
</div>
</div>
{% endblock %}

ecommerce/templates/login.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="container">
<h2 class="text-center mt-5">Login Your Account</h2>
<form method="POST">

{% csrf_token %}

<div class="mb-3 mx-auto " style="width:40%">
  <label  class="form-label">Username</label>
  <input type="text" class="form-control" name="u" placeholder="Enter the username">
</div>

    <div class="mb-3 mx-auto" style="width:40%">
  <label  class="form-label">Password</label>
  <input type="password" class="form-control" name="p" placeholder="Enter the Password">
</div>
      <div class="mb-3 text-center">
  <input type="submit" value="submit">
</div>
</form>
{% if messages %}
<ul class="messages text-danger fs-4 text-capitalize">
    {% for message in messages %}
    <li>{{ message }}</li>
    {% endfor %}
</ul>
{% endif %}
    </div>
{% endblock %}

ecommerce/templates/order.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<h2 class="text-center mt-5">Billing Details....</h2>
<div class="container">
<form method="POST">

{% csrf_token %}

<div class="mb-3 mx-auto" style="width:60%">
  <label  class="form-label">Address</label>
  <input type="text" class="form-control" name="a" placeholder="Enter the Address">
</div>

<div class="mb-3 mx-auto" style="width:60%">
  <label  class="form-label">Phone</label>
  <input type="number" class="form-control" name="p" placeholder="Enter the Phone number">
</div>

<div class="mb-3 mx-auto" style="width:60%">
  <label  class="form-label">Pin</label>
  <input type="number" class="form-control" name="pi" placeholder="Enter the Pincode">
</div>

<div class="mb-3 text-center">
  <input type="submit"  value="submit">
</div>

</form>

</div>

{% endblock %}

ecommerce/templates/payment.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="container" style="margin-bottom:100px">
    <form action="http://127.0.0.1:8000/cart/status/{{payment.name}}" method="POST" class="fs-4 text-center p-5">
<script
   src="https://checkout.razorpay.com/v1/checkout.js"
    data-key="rzp_test_nnlp4dQwHnRlZv" // Enter the Test API Key ID generated from Dashboard → Settings → API Keys
    data-amount="{{payment.amount}}" // Amount is in currency subunits. Hence, 29935 refers to 29935 paise or ₹299.35.
    data-currency="INR"// You can accept international payments by changing the currency code. Contact our Support Team to enable International for your account
    data-order_id="{{payment.id}}"// Replace with the order_id generated by you in the backend.
    data-buttontext="Pay with Razorpay"
    data-name="Acme Corp"
    data-description="A Wild Sheep Chase is the third novel by Japanese author Haruki Murakami"
    data-image="https://example.com/your_logo.jpg"
    data-prefill.name="{{payment.name}}"
    data-prefill.email="gaurav.kumar@example.com"
    data-theme.color="#F37254"
></script>
<input type="hidden" custom="Hidden Element" name="hidden"/>
</form>
</div>
{% endblock %}

ecommerce/templates/payment_status.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="container text-center mt-5" style="margin-bottom:100px">

    {% if status == True %}
     <h2>Payment Successful</h2>
    {% else %}
     <h2>Payment Failed.Please try again ...</h2>
    {% endif %}
</div>
{% endblock %}

ecommerce/templates/product.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<div class="row mt-3">
    <div class="col-12">
    <img src="{{cat.image.url}}" height="400px" width="100%"></div>
</div>

    <div class="row mt-3 px-3" style="margin-bottom:100px">
        <div class="col-12">
            <h3 class="text-center fw-bold text=light mt-5 mb-5 shadow">{{cat.name}}</h3>
            <p style="text-align:justify;line-height:2.5" class="fs-5">{{cat.desc}}</p></div>
    </div>


<div class="container mt-5" style="margin-bottom:100px">

    <div class="row">
{% for i in product %}
        <div class="col-sm-4" >
      <div class="card mx-auto border border-3 border-light" style="width:20rem; background-color:#bd58db">
  <img src="{{i.image.url}}"  height="200px" width="100%" class="card-img-top" alt="...">
  <div class="card-body text-center">
    <h5 class="card-title">{{i.name}}</h5>



    <a href="{% url 'shop:details' i.id %}" class="btn btn-secondary">Details</a>
  </div>
</div>
        </div>

        {% endfor %}


    </div>
</div>

{% endblock %}

ecommerce/templates/register.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="container" style="margin-bottom:100px">
<h2 class="text-center">Register page</h2>
<form method="POST">

{% csrf_token %}

<div class="mb-3 mx-auto" style="width:60%">
  <label  class="form-label">Username</label>
  <input type="text" class="form-control" name="u" placeholder="Enter the username">
</div>

    <div class="mb-3 mx-auto" style="width:60%">
  <label  class="form-label">Password</label>
  <input type="password" class="form-control" name="p" placeholder="Enter the Password">
</div>

        <div class="mb-3 mx-auto" style="width:60%">
  <label  class="form-label">Confirm Password</label>
  <input type="password" class="form-control" name="cp" placeholder="Enter the Confirm Password">
</div>

    <div class="mb-3 mx-auto" style="width:60%">
  <label  class="form-label">Firstname</label>
  <input type="text" class="form-control" name="f" placeholder="Enter the firstname">
</div>

    <div class="mb-3 mx-auto" style="width:60%">
  <label  class="form-label">Lastname</label>
  <input type="text" class="form-control" name="l" placeholder="Enter the lastname">
</div>

    <div class="mb-3 mx-auto" style="width:60%">
  <label  class="form-label">Email</label>
  <input type="email" class="form-control" name="e" placeholder="Enter the email">
</div>
  <div class="mb-3  text-center">
  <input type="submit" value="submit">
</div>

</form>
    </div>
{% endblock %}

ecommerce/templates/search.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<h3 class="text-center"> You have searched for {{q}}</h3>
<div class="container mt-5" style="margin-bottom:100px">
{% if product == None %}
<!--    if no query entered by the user-->
    <h5 class="text-center">No Results Found</h5>
    {% else %}
    <div class="row">
{% for i in product %}
        <div class="col-sm-4">
      <div class="card mx-auto border border-3 border-light" style="width:100%; background-color:#ffcccc">
  <img src="{{i.image.url}}"  height="200px" width="100%" class="card-img-top" alt="...">
  <div class="card-body text-center">
    <h5 class="card-title">{{i.name}}</h5>
<!--    <h5 class="card-title">{{i.price}}</h5>-->
<!--    <h5 class="card-title">{{i.stock}}</h5>-->
<!--    <h5 class="card-title">{{i.available}}</h5>-->
    <a href="{% url 'shop:details' i.id %}" class="btn btn-primary">Details</a>


  </div>
</div>
        </div>
        {% empty %}
<!--        if product sequence empty...-->
            <h5 class="text-center">No Results Found</h5>
        {% endfor %}


    </div>
</div>
{% endif %}
{% endblock %}

ecommerce/templates/yourorders.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="container text-center mt-5">
<div class="row">
  <h3 class="text-center"><i>Name of the Customer:{{user.username}}</i></h3>
  {% for i in orders %}
  <div class="card mb-3 mx-auto" style="max-width: 540px; background-color:#c5ebda">
  <div class="row g-0">
    <div class="col-md-4 p-3">
      <img src="{{i.product.image.url}}" class="img-fluid rounded-start" height="200px" width="100%" alt="...">
    </div>
    <div class="col-md-8">
      <div class="card-body ">
        <h5 class="card-title">Product Name: <i>{{i.product.name}}</i></h5>
        <h6 class="card-title">Product Price: {{i.product.price}}</h6>
        <h6 class="card-title">No.of.items: {{i.no_of_items}}</h6>
        <h6 class="card-title">Delivery address: {{i.address}}</h6>
        <h6 class="card-title">Phone: {{i.phone_no}}</h6>
        <h6 class="card-title">Order_on: {{i.ordered_date}}</h6>
        <h6 class="card-title">Delivery status: <span class="text-danger">{{i.delivery_status}}</span></h6>



      </div>
    </div>
  </div>
</div>
  {% endfor %}
</div>

    </div>
{% endblock %}